version: "3.8"
services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        environment:
            - COLLECTOR_ZIPKIN_HOST_PORT=:9411
        ports:
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "4317:4317"
            - "4318:4318"
            - "14250:14250"
            - "14268:14268"
            - "14269:14269"
            - "9411:9411"
        volumes:
            - jaeger-data:/data # Mount volume to persist data

volumes:
    jaeger-data:
